---
- name: Pre-reqs setup task 3
  import_tasks: pre_setup.yml
  when: pre_setup
  tags: pre_setup

- name: Configure firewall 3
  import_tasks: "{{ item }}"
  with_first_found:
    - "configure_firewall3_{{ os_distrib_version }}.yml"
    - "configure_firewall3_{{ os_family_version }}.yml"
    - "configure_firewall3_{{ os_distrib }}.yml"
    - "configure_firewall3_{{ os_family }}.yml"
  when: firewall and (not remove_firewall)
  tags: firewall

- name: Install HA packages
  package:
    name: [keepalived,haproxy,psmisc]  # killall in psmisc
    state: present

- name: "Copy etc-keepalived-keepalived.master.conf"
  template:
    src: "etc-keepalived-keepalived.master.conf.j2"
    dest: "/etc/keepalived/keepalived.conf"
    owner: root
    group: root
    mode: 0644
  when: inventory_hostname in groups['kube_masters'][0]

- name: "Copy etc-keepalived-keepalived.backup.conf"
  template:
    src: "etc-keepalived-keepalived.backup.conf.j2"
    dest: "/etc/keepalived/keepalived.conf"
    owner: root
    group: root
    mode: 0644
  when: (inventory_hostname in groups['kube_masters'][1]) or (inventory_hostname in groups['kube_masters'][2])

- name: "Copy etc-haproxy-haproxy.cfg"
  template:
    src: "etc-haproxy-haproxy.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"
    owner: root
    group: root
    mode: 0644

- name: Enable keepalived service
  systemd:
    name: keepalived
    enabled: yes
    state: started

- name: Restart haproxy service
  systemd:
    name: haproxy
    state: restarted
    daemon_reload: yes
