- hosts: master
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: initialize the cluster
      # shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      shell: kubeadm init >> ~/cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: ~/.kube/config
        remote_src: yes

    - name: Deploy calico
      command: curl https://docs.projectcalico.org/manifests/calico.yaml -o ~/calico.yaml
      
    - stat: path=~/calico.yaml
      register: p

    - name: install Pod network
      shell: kubectl apply -f ~/calico.yaml >> ~/pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
      when: p.stat.exists
