---
- hosts: kube
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
   - name: Delete cluster
     command: "kubeadm reset -f"
     register: output

   - name: Output delete cluster
     debug:
       var: output.stdout
