---
# Define values to ansible distrib, version, family facts
- name: Define values to ansible distrib, version, family facts
  hosts: all
  # remote_user: <user>
  become: yes
  become_method: sudo
  gather_facts: yes
  tags: ["always", ver]
  tasks:
    # Set facts (as example facts from Astra Linux 1.7 and CentOS 8)
    - name: Set fact - os_distrib_version
      set_fact:
        os_distrib_version: "{{ ansible_distribution | replace(' ', '') | lower }}{{ ansible_distribution_major_version | lower}}"  # "astralinux1" "centos8"
    - name: Set fact - os_family_version
      set_fact:
        os_family_version: "{{ ansible_os_family | replace(' ', '') | lower }}{{ ansible_distribution_major_version  | lower }}"  # "astralinux1" "redhat8"
    - name: Set fact - os_distrib_version
      set_fact:
        os_distrib: "{{ ansible_distribution | replace(' ', '') | lower }}"  # "astralinux" "centos"
    - name: Set fact - os_family_version
      set_fact:
        os_family: "{{ ansible_os_family | replace(' ', '') | lower }}"  # "astralinux" "redhat"
    - name: Print os_distrib_version
      ansible.builtin.debug:
        msg: os_distrib_version = {{ os_distrib_version }}

# OS Prepare
- name: OS Prepare
  hosts: all
  # remote_user: <user>
  become: yes
  become_method: sudo
  gather_facts: no
  pre_tasks:
    - name: include OS specific vars
      include_vars: "{{ playbook_dir }}/vars/{{ os_distrib_version }}.yml"
      tags: ["always"]
  roles:
    - role: os-prepare
      when: os_prepare
  tags: os_prep

# Kubernetes Setup
- name: Kubernetes Setup
  hosts: kube
  # remote_user: <user>
  become: yes
  become_method: sudo
  gather_facts: no
  pre_tasks:
    - name: include OS specific vars
      include_vars: "{{ playbook_dir }}/vars/{{ os_distrib_version }}.yml"
      tags: ["always"]
  roles:
    - role: kubernetes-setup
      when: kubernetes_setup
  tags: kube_set

# HA Setup
- name: HA Setup
  hosts: kube-masters
  # remote_user: <user>
  become: yes
  become_method: sudo
  gather_facts: no
  pre_tasks:
    - name: include OS specific vars
      include_vars: "{{ playbook_dir }}/vars/{{ os_distrib_version }}.yml"
      tags: ["always"]
  roles:
    - role: ha-setup
      when: ha_setup
  tags: ha_set
