---
# Set os_distrib_version
- name: Set os_distrib_version
  hosts: all
  # remote_user: <user>
  become: yes
  become_method: sudo
  gather_facts: yes
  tags: ["always"]
  tasks:
    # Set facts (as example facts from Astra Linux 1.7 and CentOS 8)
    - name: Set fact - os_distrib_version
      set_fact:
        os_distrib_version: "{{ ansible_distribution | replace(' ', '') }}{{ ansible_distribution_major_version }}"  # "AstraLinux1" "CentOS8"

    # - name: Set fact - os_family_version
    #   set_fact:
    #     os_family_version: "{{ ansible_os_family | replace(' ', '') }}{{ ansible_distribution_major_version }}"  # "AstraLinux1" "RedHat8"

    # - name: Set fact - os_distrib_version
    #   set_fact:
    #     os_distrib: "{{ ansible_distribution | replace(' ', '') }}"  # "AstraLinux" "CentOS"

    # - name: Set fact - os_family_version
    #   set_fact:
    #     os_family: "{{ ansible_os_family | replace(' ', '') }}"  # "AstraLinux" "RedHat"

# OS Prepare
- name: OS Prepare
  hosts: all
  # remote_user: <user>
  become: yes
  become_method: sudo
  gather_facts: no
  pre_tasks:
    - name: include OS specific vars
      include_vars: "{{ playbook_dir }}/{{ os_distrib_version }}.yml"
      tags: ["always"]
  roles:
    - os-prepare
  when: os_prepare
  tags: os_prep

# Kubernetes Setup
- name: Kubernetes Setup
  hosts: kube
  # remote_user: <user>
  become: yes
  become_method: sudo
  gather_facts: no
  pre_tasks:
    - name: include OS specific vars
      include_vars: "{{ playbook_dir }}/{{ os_distrib_version }}.yml"
      tags: ["always"]
  roles:
    - kubernetes-setup
  when: kubernetes_setup
  tags: kube_set

# HA Setup
- name: HA Setup
  hosts: kube-masters
  # remote_user: <user>
  become: yes
  become_method: sudo
  gather_facts: no
  pre_tasks:
    - name: include OS specific vars
      include_vars: "{{ playbook_dir }}/{{ os_distrib_version }}.yml"
      tags: ["always"]
  roles:
    - ha-setup
  when: ha_setup
  tags: ha_set
