# ansible-playbook k8s_init_cluster.yml --extra-vars "mc=ХХХ"
# Examples commands (mc):
#   kubeadm init
#   kubeadm init --pod-network-cidr=10.244.0.0/16
#   kubeadm init --control-plane-endpoint pp-vip-k8s.mydomen.com:8443 --upload-certs --pod-network-cidr 10.244.0.0/16
---
- hosts: kube_masters[0]
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Initialize the cluster
      shell: "{{ mc }} 2>&1 | tee ~/cluster_init.log"
      args:
        chdir: $HOME
        creates: cluster_init.log
      register: output

    - name: Output init cluster
      debug:
        msg: "{{ output.stdout.split('\n') }}"

    - name: Configure k8s administrators
      block:
        - name: Create .kube directory
          file:
            path: "/home/{{ item }}/.kube"
            state: directory
            mode: 0755
          loop: "{{ k8s_admins }}"

        - name: Copy admin.conf to user's kube config
          copy:
            src: "/etc/kubernetes/admin.conf"
            dest: "/home/{{ item }}/.kube/config"
            remote_src: yes
          loop: "{{ k8s_admins }}"
      when: k8s_admins | length > 0

    - name: Setup Calico
      block:
        - name: Add docker repository
          get_url:
            url: "https://docs.projectcalico.org/manifests/calico.yaml"
            dest: "~/calico.yaml"
          
        - stat: "path=~/calico.yaml"
          register: p

        - name: Install calico
          shell: "kubectl apply -f ~/calico.yaml 2>&1 | tee ~/install_calico.log"
          args:
            chdir: $HOME
            creates: install_calico.log
          when: p.stat.exists
