# ansible-playbook k8s_init_cluster.yml --extra-vars "mc=ХХХ"
# Examples commands (mc):
#   kubeadm init
#   kubeadm init --pod-network-cidr=10.244.0.0/16
#   kubeadm init --control-plane-endpoint pp-vip-k8s.mydomen.com:8443 --upload-certs --pod-network-cidr 10.244.0.0/16
---
- hosts: kube_masters[0]
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Check list k8s admins
      fail: 
        msg: "ERROR: List k8s administrators is empty (var k8s_admins)"
      when: not (k8s_admins | length > 0)

    - name: Initialize the cluster
      shell: "{{ mc }} 2>&1 | tee ~/cluster_init.log"
      args:
        chdir: $HOME
      register: output

    - name: Output init cluster
      debug:
        msg: "{{ output.stdout.split('\n') }}"

    - name: Configure k8s administrators
      include_tasks: configure_k8s_admin.yml
      loop: "{{ k8s_admins }}"

    - name: Setup Calico
      become: yes
      become_user: "{{ k8s_admins[0] }}"
      become_method: sudo
      block:
        - name: Download calico.yaml
          get_url:
            url: "https://docs.projectcalico.org/manifests/calico.yaml"
            dest: "~/calico.yaml"
          
        - stat: "path=~/calico.yaml"
          register: p

        - name: Install calico (execute )
          shell: "kubectl apply -f ~/calico.yaml 2>&1 | tee ~/install_calico.log"
          args:
            chdir: $HOME
          register: output_calico
          when: p.stat.exists

        - name: Output install calico
          debug:
            msg: "{{ output_calico.stdout.split('\n') }}"
