# ansible-playbook k8s_init_cluster.yml
# Examples INIT commands:
#   kubeadm init
#   kubeadm init --pod-network-cidr=10.244.0.0/16
#   kubeadm init --control-plane-endpoint pp-vip-k8s.mydomen.com:8443 --upload-certs --pod-network-cidr 10.244.0.0/16
---
- hosts: kube_masters,!kube_masters[0]
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Include join commands
      include_vars: "{{ playbook_dir }}/vars/join_commands.yml"

    - name: Join additional master to the cluster
      shell: "{{ join_master_cmd }} 2>&1 | tee ~/cluster_init.log"
      args:
        chdir: $HOME
        creates: cluster_init.log

    - name: Configure k8s administrators
      block:
        - name: Create .kube directory
          file:
            path: "/home/{{ item }}/.kube"
            state: directory
            mode: 0755
          loop: "{{ k8s_admins }}"

        - name: Copy admin.conf to user's kube config
          copy:
            src: "/etc/kubernetes/admin.conf"
            dest: "/home/{{ item }}/.kube/config"
            remote_src: yes
          loop: "{{ k8s_admins }}"
      when: k8s_admins | length > 0
