---
- hosts: kube_masters,!kube_masters[0]
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Check list k8s admins
      fail: 
        msg: "ERROR: List k8s administrators is empty (var k8s_admins)"
      when: not (k8s_admins | length > 0)

    - name: Include join commands
      include_vars: "{{ playbook_dir }}/vars/join_commands.yml"

    - name: Join additional master to the cluster
      shell: "{{ join_master_cmd }} 2>&1 | tee ~/cluster_init.log"
      args:
        chdir: $HOME
      register: output

    - name: Output init cluster
      debug:
        msg: "{{ output.stdout.split('\n') }}"

    - name: Configure k8s administrators
      include_tasks: configure_k8s_admin.yml
      loop: "{{ k8s_admins }}"
