---
- hosts: kube
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: copy /etc/resolv.conf to remote host
      copy:
        src: /etc/resolv.conf
        dest: /etc/

    - name: copy /etc/hosts to remote host
      copy:
        src: /etc/hosts
        dest: /etc/
                