---
- hosts: kube
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: copy /etc/environment to remote host
      copy:
        src: /etc/environment
        dest: /etc/

    - name: copy /etc/profile.d/http_proxy.sh to remote host
      copy:
        src: /etc/profile.d/http_proxy.sh
        dest: /etc/profile.d/
        mode: 755

    - name: copy /etc/yum.conf to remote host
      copy:
        src: /etc/yum.conf
        dest: /etc/
