---
- name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
  shell: "swapoff -a"

- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+.*)$'
    replace: '# \1'
