---
- name: "Copy kubernetes.list"
  ansible.builtin.template:
    src: 'kubernetes.repo.astralinux1.j2'
    dest: /etc/apt/sources.list.d/kubernetes.list
    owner: root
    group: root
    mode: 0644

- name: Create keyrings directory
  file: path=/usr/share/keyrings state=directory mode=0755

- name: "Copy kubernetes-archive-keyring.gpg"
  copy:
    src: "{{ playbook_dir }}/files/kubernetes-archive-keyring.gpg"
    dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg
    owner: root
    group: root
    mode: 0644

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
