---
- name: Install Docker from Astra repo
  ansible.builtin.package:
    name: [docker.io]
    state: present

- name: Create other directories required
  ansible.builtin.file:
    path: "{{ dir_name }}"
    state: directory
  loop:
    - /etc/docker
    - /etc/systemd/system/docker.service.d
  loop_control:
    loop_var: dir_name

- name: Set cgroup driver as systemd
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644

- name: Start and enable docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
    daemon_reload: yes

- name: Setup Docker Proxy
  ansible.builtin.template:
    src: docker-proxy.j2
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
  when: setup_proxy

- name: Restart docker service
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: yes
