- hosts: kube
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: "Allow ports"
      ufw:
        rule: allow
        port: '{{ item }}'
        proto: tcp
      loop:
        - '8443'
        - '6443'
        - '443'
        - '10250'
        - '10251'
        - '10252'
        - '4789'
        - '5473'
        - '179'
        - '8285'
        - '8472'
    - name: "Allow ports 2379:2380"
      ufw:
        rule: allow
        port: 2379:2380
        proto: tcp
    - name: "Allow ports 30000:32767"
      ufw:
        rule: allow
        port: 30000:32767
        proto: tcp
