# Installation from the vanilla repository. On 1.7.2, there is a problem during installation, so it's better to install from packages from the Astra repository (astra_k8s_install_packages1.yml).
- hosts: kube
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: "Copy kubernetes.list"
      copy:
        src: "{{ playbook_dir }}/files/kubernetes.list"
        dest: /etc/apt/sources.list.d/kubernetes.list
        owner: root
        group: root
        mode: 0644

    - name: Create keyrings directory
      file: path=/usr/share/keyrings state=directory mode=0755

    - name: "Copy kubernetes-archive-keyring.gpg"
      copy:
        src: "{{ playbook_dir }}/files/kubernetes-archive-keyring.gpg"
        dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg
        owner: root
        group: root
        mode: 0644

    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes

    - name: Install k8s packages
      apt:
        # name: [kubelet,kubeadm,kubectl]
        name: [kubelet=1.23.4-00,kubeadm=1.23.4-00,kubectl=1.23.4-00]
        state: present

    - name: Hold packages
      shell: "apt-mark hold kubelet kubeadm kubectl"

    - name: Enable kubelet service
      systemd:
        name: kubelet
        enabled: yes
        state: started
