- hosts: kube
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
