---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: 'Install Chrony'
      package:
        name: 'chrony'
        state: 'present'

    - name: Start service chronyd
      systemd:
        name: chronyd
        enabled: yes
        state: started
