- hosts: kube
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Install Docker from Astra repo
      package:
        name: [docker.io]
        state: present

    - name: "Copy docker config"
      copy:
        src: /home/username/k8s-pre-bootstrap/files/daemon.json
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: 0644

    - name: Start and enable docker service
      systemd:
        name: docker
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Restart docker service
      systemd:
        name: docker
        state: restarted
        daemon_reload: yes
